### ISSUE TITLE
Todo App demo is broken

### ISSUE THREAD

**Issue by czescwojtek** [turtle-DB/turtle-db.github.io#1]
Hey there,

The demo page (https://turtle-db.github.io/demo) is broken due to CORS policy. There's log in console saying: 'Sync To Error: Failed to connect to server'.
On top of that the 'https://tortoisedbdemo.online/connect', which is server URL I'm guessing, fails anyway.

**Comment by adamclark64** [comment]
```
Failed to load resource: net::ERR_CERT_DATE_INVALID
turtleDB.min.js:8 Sync From Error: Failed to connect to server
```
comes up in the terminal when "sync" button is pressed
